# Simple Teleportation config file
# Plugin by Le Duy Quang (github.com/leduyquang753)

# If you changed this file, restart the server to take effect.

# This enables teleportation to the Nether, and The End.
nether: true
theend: true

# This allows the player to teleport even they are in The End.
allowtpinend: false

# Fair-play mode: Ops cannot type the commands that are not enabled, just like normal players.
fairplay: false

# HOME LOCATIONS SECTION
# Only change this if you know what this is all about.
# Section structure:
# locations:
#   [player_name]:
#      x: [The x of home, integer]
#      y: [The y of home, integer]
#      z: [The z of home, integer]
#      yaw: [The horizontal orientation]
#      pitch: [The vertical orientation]
locations:
 Example:
   x: 0
   y: 100
   z: 0
   yaw: 0
   pitch: 0